[package]
name = "ngctl-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
errno = "*"
socket2 = "*"
libc = "*"

[build-dependencies]
bindgen = "0.59.2"
